config/routes.rb
Greasyfork::Application.routes.draw do

	scope "(:locale)", locale: /de|en|es|fr|fr\-CA|id|it|ja|nl|pl|pt-BR|ru|zh\-CN|zh\-TW/ do

		get '/users', :to => 'users#index', :as => 'users'
		get '/users/webhook-info', :to => 'users#webhook_info', :as => 'user_webhook_info'
		post 'users/webhook-info', :to => 'users#webhook_info'
		get '/users/edit_sign_in' => 'users#edit_sign_in', :as => 'user_edit_sign_in'
		delete '/users/identities' => 'users#delete_identity', :as => 'user_delete_identity'
		put '/users/identities' => 'users#update_identity', :as => 'user_update_identity'
		put '/users/remove_password' => 'users#remove_password', :as => 'user_remove_password'
		put '/users/update_password' => 'users#update_password', :as => 'user_update_password'

		get '/external_login', :as => 'external_login', to: 'home#external_login'

		devise_for :users, :skip => :registrations, :controllers => { :sessions => "sessions" }
		devise_scope :user do
			resource :registration,
			only: [:new, :create, :edit, :update],
			path: 'users',
			path_names: { new: 'sign_up' },
			controller: :registrations,
			as: :user_registration do
				get :cancel
			end
		end
		devise_scope :user do
			get '/users/sign_out' => 'sessions#destroy'
			get '/auth/:provider/callback', to: 'sessions#omniauth_callback', :as => 'omniauth_callback'
			post '/auth/:provider/callback', to: 'sessions#omniauth_callback'
			get '/auth/failure', to: 'sessions#omniauth_failure'
			get '/auth/failure2', to: 'sessions#omniauth_failure'
			post '/auth/name_conflict', to: 'sessions#name_conflict'
		end

		root :to => "home#index"

		get 'scripts/sync_additional_info_form', :to => 'scripts#sync_additional_info_form', :as => 'script_sync_additional_info_form'
		resources :scripts, :only => [:index, :show] do
			get 'code.meta.js', :to => 'scripts#meta_js', :locale => nil
			get 'code.user.js', :to => 'scripts#user_js', :locale => nil

			get 'code/:name.user.js', :to => 'scripts#user_js', :as =>  'user_js', :locale => nil
			get 'code/:name.js', :to => 'scripts#user_js', :as =>  'library_js', :locale => nil
			get 'code/:name.meta.js', :to => 'scripts#meta_js', :as =>  'meta_js', :locale => nil
			match 'code/:name.meta.js', :to => 'scripts#meta_js', :locale => nil, :via => :options
			get 'code(.:format)', :to => 'scripts#show_code', :as =>  'show_code', :constraints => {:format => /.*/}
			get 'feedback(.:format)', :to => 'scripts#feedback', :as =>  'feedback'
			get 'sync(.:format)', :to => 'scripts#sync', :as =>  'sync'
			patch 'sync_update(.:format)', :to => 'scripts#sync_update', :as =>  'sync_update'
			post 'install-ping', :to => 'scripts#install_ping', :as => 'install_ping', :locale => nil
			get 'diff', :to => 'scripts#diff', :as => 'diff', :constraints => lambda{ |req| !req.params[:v1].blank? and !req.params[:v2].blank? }
			get 'delete(.:format)', :to => 'scripts#delete', :as => 'delete'
			post 'delete(.:format)', :to => 'scripts#do_delete', :as => 'do_delete'
			get 'undelete(.:format)', :to => 'scripts#undelete', :as => 'undelete'
			post 'undelete(.:format)', :to => 'scripts#do_undelete', :as => 'do_undelete'
			get 'stats(.:format)', :to => 'scripts#stats', :as => 'stats'
			get 'derivatives', :as => 'derivatives'
			collection do
				get 'by-site(.:format)', :action => 'by_site', :as => 'site_list'
				get 'by-site/:site(.:format)', :action => 'index', :as => 'by_site', :constraints => {:site => /.*/}
				get 'under-assessment(.:format)', :action => 'under_assessment', :as => 'under_assessment'
				get 'reported(.:format)', :action => 'reported', :as => 'reported'
				get 'libraries(.:format)', :action => 'libraries', :as => 'libraries'
				get 'search(.:format)', :action => 'search', :as => 'search'
				get 'minified(.:format)', :action => 'minified', :as => 'minified'
				get 'code-search(.:format)', :action => 'code_search', :as => 'code_search'
			end
			resources :script_versions, :only => [:create, :new, :show, :index], :path => 'versions'
		end
		resources :script_versions, :only => [:create, :new]
		get 'script_versions/additional_info_form', :to => 'script_versions#additional_info_form', :as => 'script_version_additional_info_form'
		resources :users, :only => :show do
			post 'webhook'
			resources :script_sets, :only => [:create, :new, :edit, :update, :destroy], :path => 'sets'
		end
		post 'script_sets/add_to_set', :to => 'script_sets#add_to_set', :as => 'add_to_script_set'

		get 'import', :to => 'import#index', :as => 'import_start'
		get 'import/userscriptsorg', :to => 'import#userscriptsorg', :as => 'import_userscriptsorg'
		post 'import/verify', :to => 'import#verify', :as => 'import_verify'
		post 'import/add', :to => 'import#add', :as => 'import_add'
		get 'import/url', :to => 'import#url', :as => 'import_url'

		get 'help', :to => 'help#index', :as => 'help'
		get 'help/allowed-markup', :to => 'help#allowed_markup', :as => 'help_allowed_markup'
		get 'help/code-rules', :to => 'help#code_rules', :as => 'help_code_rules'
		get 'help/contact', :to => 'help#contact', :as => 'help_contact'
		get 'help/credits', :to => 'help#credits', :as => 'help_credits'
		get 'help/disallowed-code', :to => 'help#disallowed_code', :as => 'help_disallowed_code'
		get 'help/external-scripts', :to => 'help#external_scripts', :as => 'help_external_scripts'
		get 'help/installing-user-scripts', :to => 'help#installing_user_scripts', :as => 'help_installing_user_scripts'
		get 'help/rewriting', :to => 'help#rewriting', :as => 'help_rewriting'
		get 'help/meta-keys', :to => 'help#meta_keys', :as => 'help_meta_keys'

		post 'preview-markup', :to => 'home#preview_markup', :as => 'preview_markup'

		resources :moderator_actions, :only => [:index]

	end

	get 'sso', :to => 'home#sso'
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
	before_filter :authorize_for_moderators_only, :only => [:disallowed_code]
end

app/helpers/help_helper.rb
module HelpHelper
end

app/views/help/allowed_markup.html.erb
<%- title t('common.allowed_elements_and_attributes_title') %>
<%- description 'Elements and attributes allowed when posting to Greasy Fork.' %>

<p><%=t('common.allowed_elements_intro')%></p>

<ul id="help-allowed-elements">
	<li>* (name, title)</li>
	<li>a (href)</li>
	<li>abbr</li>
	<li>b</li>
	<li>blockquote (cite)</li>
	<li>br</li>
	<li>center</li>
	<li>cite</li>
	<li>code</li>
	<li>dd</li>
	<li>del</li>
	<li>dfn</li>
	<li>div</li>
	<li>dl</li>
	<li>dt</li>
	<li>em</li>
	<li>h1</li>
	<li>h2</li>
	<li>h3</li>
	<li>h4</li>
	<li>h5</li>
	<li>h6</li>
	<li>hr</li>
	<li>i</li>
	<li>ins</li>
	<li>img (alt, height, src (https), width)</li>
	<li>kbd</li>
	<li>li</li>
	<li>mark</li>
	<li>ol</li>
	<li>p</li>
	<li>pre</li>
	<li>q (cite)</li>
	<li>rp</li>
	<li>rt</li>
	<li>ruby</li>
	<li>s</li>
	<li>samp</li>
	<li>small</li>
	<li>span</li>
	<li>strike</li>
	<li>strong</li>
	<li>tt</li>
	<li>table</li>
	<li>tbody</li>
	<li>tfoot</li>
	<li>thead</li>
	<li>td</li>
	<li>th</li>
	<li>tr</li>
	<li>sub</li>
	<li>sup</li>
	<li>time (datetime, pubdate)</li>
	<li>u</li>
	<li>ul</li>
	<li>var</li>
</ul>

<p><%=t('common.allowed_elements_extra_info')%></p>

app/views/help/code_rules.html.erb
<%- title 'Code rules' %>
<%- description 'Rules and restrictions for code posted to Greasy Fork.' %>

<p>These are the requirements for scripts posted to Greasy Fork. These are intended to keep Greasy Fork a safe and useful place for user scripts. Any script falling outside these requirements may be deleted by Greasy Fork moderators.</p>

<ul>
	<li>Scripts must include a description of what they do and may not do things unreasonably outside of this description. Users must know what a script will do before installing it.</li>
	<li>Code posted to this site must not be obfuscated or minified. Users must be given the opportunity to inspect and understand a script before installing it.</li>
	<li>Libraries that a script uses should be <code>@require</code>-d, unless there's a valid technical reason not to do so. In the case that a library is included inline, it must include information as to the source of the library (e.g. a comment indicating URL and/or name and version).</li>
	<li>Your script must respect others' copyrights. This includes the script itself and any resources (for example images) it uses. If you intend on using someone else's content, abide by their licensing terms or get their permission before doing so.</li>
	<li><%=link_to "Use of external JavaScript is limited.", help_external_scripts_path()%></li>
</ul>

<p>If you notice a script that falls outside of these parameters, please report it by going to the Feedback link for that script, starting a discussion, and choosing the "Report script" option.</p>

<p>If you disagree with any of this, <%=link_to "let's talk about it", help_contact_path()%>!</p>

app/views/help/contact.html.erb
<%- title 'Contact' %>
<%- description 'How to contact someone about Greasy Fork.' %>

<p>There's a bunch of ways to talk about Greasy Fork and the things on it. If you're not sure where or how to do so, this should help.</p>

<p>Do you have a question or comment about a specific script posted on the site? If so, post a discussion from the link on the Feedback tab on that script's page. Script authors get notification on their account page of any discussions on their scripts.</p>

<p>Do you have a question or comment on Greasy Fork itself or on script development, or do you want someone to make you a script? <a href="/forum/">Posting in the forum</a> would give you the widest audience for your discussion.</p>

<p>Do you have a bug report or fully-formed idea for Greasy Fork itself (and not a specific script <em>posted on</em> Greasy Fork)? <a href="https://github.com/JasonBarnabe/greasyfork">Post it on Greasy Fork's GitHub page.</a></p>

<p>Do you have a private question or comment you would like only the admin to see? <a href="mailto:jason.barnabe@gmail.com">Send me an e-mail.</a></p>

app/views/help/credits.html.erb
<%- title 'Credits - Greasy Fork' %>

<p>Greasy Fork would not be possible without the authors who contribute scripts.</p>

<p>Greasy Fork itself is built by <a href="https://github.com/JasonBarnabe/greasyfork/graphs/contributors">these people</a> with the help of all those who report bugs and suggest improvements.</p>

<p>Greasy Fork was translated by <a href="https://www.transifex.com/organization/greasy-fork/team/21359/">the Greasy Translation Force on Transifex</a>:</p>

<ul>
	<% Locale.where(:ui_available => true).joins(:locale_contributors).order(:code).uniq.each do |locale| %>
		<li><%=locale.native_name%> (<%=locale.code%>): <%=locale.locale_contributors.map{|lc| lc.transifex_user_name}.join(', ')%></li>
	<% end %>
</ul>

<p>Discussion icons are from <a href="https://www.iconfinder.com/search/?q=iconset:softwaredemo">"Vista Style Base Software"</a> by <a href="http://www.icons-land.com/">Icons Land</a>.</p>

app/views/help/disallowed_code.html.erb
<p>Code patterns that will get blocked automatically. Users posting this will get the message "Name exception (code)".</p>

<p>This is a private list for moderator eyes only, because malicious people could easily craft their scripts to get around these blocks if they knew what they were.</p>

<table>
	<thead>
		<tr>
			<th>Code</th>
			<th>Pattern</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
		<% DisallowedCode.all.each do |dc| %>
			<tr>
				<td><%=dc.ob_code%></td>
				<td><code><%=dc.pattern%></code></td>
				<td><%=dc.description%></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/help/external_scripts.html.erb
<%- title 'Greasy Fork policy on external scripts' %>
<%- description "Greasy Fork's policy on external scripts included in submitted user scripts, for example with @require." %>

<h1>External scripts</h1>

<p>User scripts have the technical ability to load and execute other scripts. The <a href="http://wiki.greasespot.net/Metadata_Block#.40require"><code>@require</code></a> metadata key is the most straightforward way to accomplish this, but scripts can also, for example, use an XmlHttpRequest to download a script and then inject it into the DOM.</p>

<p>While this is a useful feature and most script authors use this for legitimate purposes, it can also be used maliciously. One of the core principles of Greasy Fork is that the user must be able to inspect the code in a script. External scripts can bypass this principle in a number of ways: they can change without warning or history, they can serve up different code to different people, and they can be used to hide malicious code in the middle of known libraries. Even if someone were to check an external script and determine it to be legitimate, that would be no guarantee that that script always has been or always will be legitimate.</p>

<p>To allow script authors to continue to use external scripts, Greasy Fork has implemented a whitelist of URL patterns that can included with a script. This whitelist consists of script locations that:</p>

<ul>
	<li>Are public</li>
	<li>Will not have their contents change frequently</li>
	<li>Would likely be useful to more than one script author</li>
</ul>

<p>The current list is:</p>

<ul>
<% AllowedRequire.all.each do |ar| %>
	<li>
		<% if ar.url.nil? %>
			<%=ar.name%>
		<% else %>
			<%=link_to ar.name, ar.url%>
		<% end %>
	</li>
<% end %>
</ul>

<p>When you post a script that uses a <code>@require</code> outside of these locations, you will be notified when you attempt to save the script. Your script will not be made public on Greasy Fork until this is resolved.</p>

<p>If the script you wish to include is a JavaScript library (for example jQuery or YUI), try to find it on one of the sites listed above. <a href="http://cdnjs.com/">cdnjs</a> and <a href="http://www.jsdelivr.com/">jsDelivr</a> in particular have a wide range of libraries available.</p>

<p>If the script you wish to include is not available on the sites above, <%=link_to 'let us know', help_contact_path()%> and we can find somewhere it is (or host it ourselves!).</p>

<p>If the script you wish to include was written by you, you can submit it as a separate entry on Greasy Fork and choosing the "Library" script type. You will be able to include this posted library in your script.</p>

app/views/help/index.html.erb
<%- title 'Help - Greasy Fork' %>
<%- description 'Help with Greasy Fork.' %>

<ul>
	<li><%=link_to 'How to install user scripts', help_installing_user_scripts_path%></li>
	<li><%=link_to 'Help with Greasemonkey', 'http://wiki.greasespot.net/Troubleshooting_(Users)'%></li>
	<li><%=link_to 'Script meta keys read by Greasy Fork', help_meta_keys_path%></li>
	<li><%=link_to 'Rules for code posted on Greasy Fork', help_code_rules_path%></li>
	<li><%=link_to 'Rules for code including external scripts', help_external_scripts_path%></li>
	<li><%=link_to 'Allowed markup for posting on Greasy Fork', help_allowed_markup_path%></li>
	<li><%=link_to 'How Greasy Fork will rewrite posted scripts', help_rewriting_path%></li>
	<li><%=link_to 'Report issue or post idea for Greasy Fork itself', 'https://github.com/JasonBarnabe/greasyfork/issues'%></li>
	<li><%=link_to 'Contact someone', help_contact_path%></li>
	<li><%=link_to 'Credits', help_credits_path%></li>
</ul>

<p>And, not really help topics, but because I have nowhere else to post these...</p>

<ul>
	<li><%=link_to 'User list', users_path%></li>
	<li><%=link_to 'Libraries', libraries_scripts_path%></li>
	<li><%=link_to 'Scripts including disallowed external scripts', under_assessment_scripts_path%></li>
	<li><%=link_to 'Reported scripts', reported_scripts_path%></li>
	<li><%=link_to 'Moderator log', moderator_actions_path%></li>
	<li><%=link_to 'Code search', code_search_scripts_path%></li>
</ul>

<% if !current_user.nil? and current_user.moderator? %>
	<p>Hey, moderators.</p>
	<ul>
		<li><%=link_to 'Disallowed code patterns', help_disallowed_code_path%></li>
	</ul>
<% end %>

<p>Greasy Fork is open source (GPLv3 licensed). You can <a href="https://github.com/JasonBarnabe/greasyfork">view its source on GitHub</a>.</p>

app/views/help/installing_user_scripts.html.erb
<%- title 'How to install user scripts' %>
<%- description 'Describes how to install user scripts from Greasy Fork.' %>

<p>How you install user scripts depends on which browser you use. Typically, you will need to install a browser extension. This is not an exhaustive list, please <%=link_to 'contact us', help_contact_path%> if you have any additions.</p>

<p>Once user scripts are enabled in your browser, it should be as simple as clicking the "Install" button on any script's page on Greasy Fork.</p>

<h2>Firefox and related</h2>
<ul>
	<li><a href="https://addons.mozilla.org/firefox/addon/greasemonkey/">Greasemonkey</a></li>
	<li><a href="https://addons.mozilla.org/firefox/addon/scriptish/">Scriptish</a></li>
</ul>

<h2>Google Chrome, Chromium, and related</h2>
<ul>
	<li><a href="https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo">Tampermonkey</a></li>
</ul>

<h2>Opera (version 15 and later)</h2>
<ul>
	<li><a href="https://addons.opera.com/extensions/details/tampermonkey-beta/">Tampermonkey</a></li>
	<li><a href="https://addons.opera.com/extensions/details/violent-monkey/">Violentmonkey</a></li>
</ul>

<h2>Opera (version 12 and earlier)</h2>
<p>Opera version 12 and earlier <a href="http://www.opera.com/docs/userjs/using/#writingscripts">supports user scripts natively</a>. <a href="https://addons.opera.com/extensions/details/violent-monkey/">Violentmonkey</a> provides a friendlier UI and better compatibility.</p>
</ul>

app/views/help/meta_keys.html.erb
<%- title 'Meta keys - Greasy Fork' %>
<%- description 'List of user script meta keys that mean something to Greasy Fork.' %>

<p>This is a list of <a href="http://wiki.greasespot.net/Metadata_Block">user script meta keys</a> that Greasy Fork will read. Keys outside of this list may be included in scripts, and will be present in the installed script, but have no effect in Greasy Fork's UI.</p>

<dl>
	<dt><%=self_link('meta-name', '@name')%></dt>
	<dd>The name of the script, used as a heading and in links. Required.</dd>

	<dt><%=self_link('meta-name-localized', '@name:XX-YY')%></dt>
	<dd>The name of the script in a specific locale, where XX is an <a href="http://www.loc.gov/standards/iso639-2/php/code_list.php">ISO 639-1 2-letter code</a> and YY is an optional <a href="https://www.iso.org/obp/ui/#search">ISO 3166 country code</a>. Overrides <code>@name</code> when the user is browsing in a matching locale.</dd>

	<dt><%=self_link('meta-description', '@description')%></dt>
	<dd>A description of what the script does. Shown as text under the script name. Required.</dd>

	<dt><%=self_link('meta-name-description', '@description:XX-YY')%></dt>
	<dd>The description of the script in a specific locale, where XX is an <a href="http://www.loc.gov/standards/iso639-2/php/code_list.php">ISO 639-1 2-letter code</a> and YY is an optional <a href="https://www.iso.org/obp/ui/#search">ISO 3166 country code</a>. Overrides <code>@description</code> when the user is browsing in a matching locale.

	<dt><%=self_link('meta-namespace', '@namespace')%></dt>
	<dd>A combination of <code>@namespace</code> and <code>@name</code> is used by user script managers to see if a script is already installed. Greasy Fork requires this field and will warn if it's changed on update.</dd>

	<dt><%=self_link('meta-version', '@version')%></dt>
	<dd>Identifier for a specific version of a script in <a href="https://developer.mozilla.org/en/docs/Toolkit_version_format">Mozilla version format</a>. Version is displayed on a script's info page. Greasy Fork requires this field and will warn if it's decremented or if it's not incremented when the script's code changes.</dd>

	<dt><%=self_link('meta-include', '@include, @exclude, @match')%></dt>
	<dd>Describe what pages the script will run on. This list will be processed, displayed on the script's info page, and used to categorize scripts.</dd>

	<dt><%=self_link('meta-require', '@require')%></dt>
	<dd>Includes external JavaScript into a script. See <%=link_to 'rules for code including external scripts', help_external_scripts_path%></dd>

	<dt><%=self_link('meta-updateURL', '@updateURL, @installURL, @downloadURL')%></dt>
	<dd>Describe how user script managers should get updates. Greasy Fork will strip these keys, which makes any script installed from Greasy Fork only update from Greasy Fork.</dd>

	<dt><%=self_link('meta-license', '@license')%></dt>
	<dd>URL for or name of the license that describes how people are allowed to copy or modify a script. Lack of license implies users can install the script for personal use, but may not redistribute it. License is displayed on a script's info page.</dd>

	<dt><%=self_link('meta-supportURL', '@supportURL')%></dt>
	<dd>URL for a page where users can get support on a script (e.g. a bug tracker, a forum, an e-mail address). Support URL is displayed on a script's feedback page.</dd>

	<dt><%=self_link('meta-contributionURL', '@contributionURL')%></dt>
	<dd>URL for a page where users can donate to the author of a script. Contribution URL is displayed on a script's feedback page.</dd>

	<dt><%=self_link('meta-contributionAmount', '@contributionAmount')%></dt>
	<dd>Suggested donation amount, used in conjunction with <code>@contributionURL</code>.</dd>
</dl>

app/views/help/rewriting.html.erb
<%- title 'Script rewriting' %>
<%- description 'A list of ways Greasy Fork may rewrite scripts.' %>

<p>Scripts posted to Greasy Fork may be rewritten in the following ways:</p>

<ul>
	<li><code>@updateURL</code>, <code>@installURL</code>, and <code>@downloadURL</code> directives will be stripped, if present. The lack of these directives means that any script installed from Greasy Fork will be updated from Greasy Fork.</li>
	<li><code>@version</code> and <code>@namespace</code> directives will inserted if the script is missing them. These directives are needed for proper updating.</li>
	<li><code>@description</code> will be inserted if a new version of a script is missing it and a previous version of the script had it.</li>
	<li>Line breaks will be converted to Unix-style line breaks (\n).</li>
</ul>