config/routes.rb
Greasyfork::Application.routes.draw do

	scope "(:locale)", locale: /de|en|es|fr|fr\-CA|id|it|ja|nl|pl|pt-BR|ru|zh\-CN|zh\-TW/ do

		get '/users', :to => 'users#index', :as => 'users'
		get '/users/webhook-info', :to => 'users#webhook_info', :as => 'user_webhook_info'
		post 'users/webhook-info', :to => 'users#webhook_info'
		get '/users/edit_sign_in' => 'users#edit_sign_in', :as => 'user_edit_sign_in'
		delete '/users/identities' => 'users#delete_identity', :as => 'user_delete_identity'
		put '/users/identities' => 'users#update_identity', :as => 'user_update_identity'
		put '/users/remove_password' => 'users#remove_password', :as => 'user_remove_password'
		put '/users/update_password' => 'users#update_password', :as => 'user_update_password'

		get '/external_login', :as => 'external_login', to: 'home#external_login'

		devise_for :users, :skip => :registrations, :controllers => { :sessions => "sessions" }
		devise_scope :user do
			resource :registration,
			only: [:new, :create, :edit, :update],
			path: 'users',
			path_names: { new: 'sign_up' },
			controller: :registrations,
			as: :user_registration do
				get :cancel
			end
		end
		devise_scope :user do
			get '/users/sign_out' => 'sessions#destroy'
			get '/auth/:provider/callback', to: 'sessions#omniauth_callback', :as => 'omniauth_callback'
			post '/auth/:provider/callback', to: 'sessions#omniauth_callback'
			get '/auth/failure', to: 'sessions#omniauth_failure'
			get '/auth/failure2', to: 'sessions#omniauth_failure'
			post '/auth/name_conflict', to: 'sessions#name_conflict'
		end

		root :to => "home#index"

		get 'scripts/sync_additional_info_form', :to => 'scripts#sync_additional_info_form', :as => 'script_sync_additional_info_form'
		resources :scripts, :only => [:index, :show] do
			get 'code.meta.js', :to => 'scripts#meta_js', :locale => nil
			get 'code.user.js', :to => 'scripts#user_js', :locale => nil

			get 'code/:name.user.js', :to => 'scripts#user_js', :as =>  'user_js', :locale => nil
			get 'code/:name.js', :to => 'scripts#user_js', :as =>  'library_js', :locale => nil
			get 'code/:name.meta.js', :to => 'scripts#meta_js', :as =>  'meta_js', :locale => nil
			match 'code/:name.meta.js', :to => 'scripts#meta_js', :locale => nil, :via => :options
			get 'code(.:format)', :to => 'scripts#show_code', :as =>  'show_code', :constraints => {:format => /.*/}
			get 'feedback(.:format)', :to => 'scripts#feedback', :as =>  'feedback'
			get 'sync(.:format)', :to => 'scripts#sync', :as =>  'sync'
			patch 'sync_update(.:format)', :to => 'scripts#sync_update', :as =>  'sync_update'
			post 'install-ping', :to => 'scripts#install_ping', :as => 'install_ping', :locale => nil
			get 'diff', :to => 'scripts#diff', :as => 'diff', :constraints => lambda{ |req| !req.params[:v1].blank? and !req.params[:v2].blank? }
			get 'delete(.:format)', :to => 'scripts#delete', :as => 'delete'
			post 'delete(.:format)', :to => 'scripts#do_delete', :as => 'do_delete'
			get 'undelete(.:format)', :to => 'scripts#undelete', :as => 'undelete'
			post 'undelete(.:format)', :to => 'scripts#do_undelete', :as => 'do_undelete'
			get 'stats(.:format)', :to => 'scripts#stats', :as => 'stats'
			get 'derivatives', :as => 'derivatives'
			collection do
				get 'by-site(.:format)', :action => 'by_site', :as => 'site_list'
				get 'by-site/:site(.:format)', :action => 'index', :as => 'by_site', :constraints => {:site => /.*/}
				get 'under-assessment(.:format)', :action => 'under_assessment', :as => 'under_assessment'
				get 'reported(.:format)', :action => 'reported', :as => 'reported'
				get 'libraries(.:format)', :action => 'libraries', :as => 'libraries'
				get 'search(.:format)', :action => 'search', :as => 'search'
				get 'minified(.:format)', :action => 'minified', :as => 'minified'
				get 'code-search(.:format)', :action => 'code_search', :as => 'code_search'
			end
			resources :script_versions, :only => [:create, :new, :show, :index], :path => 'versions'
		end
		resources :script_versions, :only => [:create, :new]
		get 'script_versions/additional_info_form', :to => 'script_versions#additional_info_form', :as => 'script_version_additional_info_form'
		resources :users, :only => :show do
			post 'webhook'
			resources :script_sets, :only => [:create, :new, :edit, :update, :destroy], :path => 'sets'
		end
		post 'script_sets/add_to_set', :to => 'script_sets#add_to_set', :as => 'add_to_script_set'

		get 'import', :to => 'import#index', :as => 'import_start'
		get 'import/userscriptsorg', :to => 'import#userscriptsorg', :as => 'import_userscriptsorg'
		post 'import/verify', :to => 'import#verify', :as => 'import_verify'
		post 'import/add', :to => 'import#add', :as => 'import_add'
		get 'import/url', :to => 'import#url', :as => 'import_url'

		get 'help', :to => 'help#index', :as => 'help'
		get 'help/allowed-markup', :to => 'help#allowed_markup', :as => 'help_allowed_markup'
		get 'help/code-rules', :to => 'help#code_rules', :as => 'help_code_rules'
		get 'help/contact', :to => 'help#contact', :as => 'help_contact'
		get 'help/credits', :to => 'help#credits', :as => 'help_credits'
		get 'help/disallowed-code', :to => 'help#disallowed_code', :as => 'help_disallowed_code'
		get 'help/external-scripts', :to => 'help#external_scripts', :as => 'help_external_scripts'
		get 'help/installing-user-scripts', :to => 'help#installing_user_scripts', :as => 'help_installing_user_scripts'
		get 'help/rewriting', :to => 'help#rewriting', :as => 'help_rewriting'
		get 'help/meta-keys', :to => 'help#meta_keys', :as => 'help_meta_keys'

		post 'preview-markup', :to => 'home#preview_markup', :as => 'preview_markup'

		resources :moderator_actions, :only => [:index]

	end

	get 'sso', :to => 'home#sso'
end

app/models/script_type.rb
class ScriptType < ActiveRecord::Base
end

app/controllers/scripts_controller.rb
require 'script_importer/script_syncer'

class ScriptsController < ApplicationController
	layout 'application', :except => [:show, :show_code, :feedback, :diff, :sync, :sync_update, :delete, :undelete, :stats, :derivatives]

	before_filter :authorize_by_script_id, :only => [:sync, :sync_update]
	before_filter :authorize_by_script_id_or_moderator, :only => [:delete, :do_delete, :undelete, :do_undelete, :derivatives]
	before_filter :check_for_locked_by_script_id, :only => [:sync, :sync_update, :delete, :do_delete, :undelete, :do_undelete]
	before_filter :check_for_deleted_by_id, :only => [:show]
	before_filter :check_for_deleted_by_script_id, :only => [:show_code, :feedback, :user_js, :meta_js, :install_ping, :diff]
	before_filter :authorize_for_moderators_only, :only => [:minified]

	skip_before_action :verify_authenticity_token, :only => [:install_ping]
	protect_from_forgery :except => [:user_js, :meta_js, :show, :show_code]

	# The value a syncing additional info will have after syncing is added but before the first sync succeeds
	ADDITIONAL_INFO_SYNC_PLACEHOLDER = '(Awaiting sync)'

	#########################
	# Collections
	#########################

	def index
		@scripts = Script.listable.includes({:user => {}, :script_type => {}, :localized_attributes => :locale, :script_delete_type => {}}).paginate(:page => params[:page], :per_page => get_per_page)
		@scripts = self.class.apply_filters(@scripts, params)

		respond_to do |format|
			format.html {
				if !params[:set].nil?
					@set = ScriptSet.find(params[:set])
				end
				@by_sites = self.class.get_top_by_sites

				@bots = 'noindex,follow' if !params[:sort].nil?
				@link_alternates = [
					{:url => url_for(params.merge({:only_path => true, :page => nil, :sort => 'created', :format => :atom})), :type => 'application/atom+xml', :title => t('scripts.listing_created_feed')},
					{:url => url_for(params.merge({:only_path => true, :page => nil, :sort => 'updated', :format => :atom})), :type => 'application/atom+xml', :title => t('scripts.listing_updated_feed')},
					{:url => url_for(params.merge({:only_path => true, :format => :json})), :type => 'application/json'},
					{:url => url_for(params.merge({:only_path => true, :format => :jsonp, :callback => 'callback'})), :type => 'application/javascript'}
				]

				if !params[:set].nil?
					if @set.favorite
						@title = t('scripts.listing_title_for_favorites', :set_name => @set.display_name, :user_name => @set.user.name)
					else
						@title = @set.display_name
						@description = @set.description
					end
				elsif params[:site] == '*' and !@scripts.empty?
					@title = t('scripts.listing_title_all_sites')
					@description = t('scripts.listing_description_all_sites')
				elsif !params[:site].nil? and !@scripts.empty?
					@title = t('scripts.listing_title_for_site', :site => params[:site])
					@description = t('scripts.listing_description_for_site', :site => params[:site])
				else
					@title = t('scripts.listing_title_generic')
					@description = t('scripts.listing_description_generic')
				end
				@canonical_params = [:page, :per_page, :set, :site, :sort]
			}
			format.atom
			format.json { render :json => @scripts.as_json(:include => :user) }
			format.jsonp { render :json => @scripts.as_json(:include => :user), :callback => clean_json_callback_param }
		end
	end

	def by_site
		@by_sites = self.class.get_by_sites
	end

	def search
		if params[:q].nil? or params[:q].empty?
			redirect_to scripts_path
			return
		end
		@bots = 'noindex,follow'
		begin
			@scripts = Script.search params[:q], :match_mode => :extended, :page => params[:page], :per_page => get_per_page, :order => self.class.get_sort(params, true), :populate => true, :includes => [:script_type, :localized_attributes => :locale]
			# make it run now so we can catch syntax errors
			@scripts.empty?
		rescue ThinkingSphinx::SyntaxError => e
			flash[:alert] = "Invalid search query - '#{params[:q]}'."
			# back to the main listing
			redirect_to scripts_path
			return
		end
		@title = t('scripts.listing_title_for_search', :search_string => params[:q])
		@feeds = {t('scripts.listing_created_feed') => {:sort => 'created'}, t('scripts.listing_updated_feed') => {:sort => 'updated'}}
		@canonical_params = [:q, :page, :per_page, :sort]
		render :action => 'index'
	end

	def libraries
		@scripts = Script.libraries
	end

	def under_assessment
		@bots = 'noindex'
		@scripts = Script.under_assessment
	end

	def reported
		@bots = 'noindex'
		@scripts = Script.reported
	end

	def minified
		@bots = 'noindex'
		@scripts = []
		Script.order(self.class.get_sort(params)).where(:locked => false).each do |script|
			sv = script.get_newest_saved_script_version
			@scripts << script if sv.appears_minified
		end
		@paginate = false
		@title = "Potentially minified user scripts on Greasy Fork"
		render :action => 'index'
	end

	def code_search
		@bots = 'noindex,follow'
		if params[:c].nil? or params[:c].empty?
			return
		end

		# get latest version for each script
		script_version_ids = Script.connection.select_values("SELECT MAX(id) FROM script_versions GROUP BY script_id")

		# check the code for the search text
		# using the escape character doesn't seem to work, yet it works from the command line. so choose something unlikely to be used as our escape character
		script_ids = Script.connection.select_values("SELECT DISTINCT script_id FROM script_versions JOIN script_codes ON rewritten_script_code_id = script_codes.id WHERE script_versions.id IN (#{script_version_ids.join(',')}) AND code LIKE '%#{Script.connection.quote_string(params[:c].gsub('É', 'ÉÉ').gsub('%', 'É%').gsub('_', 'É_'))}%' ESCAPE 'É' LIMIT 100")
		@scripts = Script.order(self.class.get_sort(params)).where(:locked => false).includes([:user, :script_type, :script_delete_type]).where(:id => script_ids)
		@paginate = false
		@title = t('scripts.listing_title_for_code_search', :search_string => params[:c])
		@canonical_params = [:c, :sort]
		render :action => 'index'
	end

	#########################
	# Single resource
	#########################

	def show
		@script, @script_version = versionned_script(params[:id], params[:version])
		return if redirect_to_slug(@script, :id)
		respond_to do |format|
			format.html {
				if !params[:version].nil?
					@bots = 'noindex'
				elsif @script.unlisted?
					@bots = 'noindex,follow'
				end
				@by_sites = self.class.get_by_sites
				@link_alternates = [
					{:url => url_for(params.merge({:only_path => true, :format => :json})), :type => 'application/json'},
					{:url => url_for(params.merge({:only_path => true, :format => :jsonp, :callback => 'callback'})), :type => 'application/javascript'}
				]
				@canonical_params = [:id, :version]
			}
			format.js {
				redirect_to @script.code_url
			}
			format.json { render :json => @script.as_json(:include => :user) }
			format.jsonp { render :json => @script.as_json(:include => :user), :callback => clean_json_callback_param }
			format.user_script_meta {
				redirect_to script_meta_js_path(params.merge({:script_id => params[:id], :name => @script.name, :format => nil}))
			}
		end
	end

	def show_code
		@script, @script_version = versionned_script(params[:script_id], params[:version])

		# some weird safari client tries to do this
		if params[:format] == 'meta.js'
			redirect_to script_meta_js_path(params.merge({:name => @script.name, :format => nil}))
			return
		end

		return if redirect_to_slug(@script, :script_id)
		respond_to do |format|
			format.html {
				@highlighted_code = nil
				if params[:version].nil?
					if !@script.syntax_highlighted_code.nil?
						@highlighted_code = @script.syntax_highlighted_code.html
					end
				else
					@bots = 'noindex'
				end
				# Generate on the fly
				if @highlighted_code.nil?
					@highlighted_code = SyntaxHighlightedCode.highlight(@script_version.rewritten_code)
				end
				if @highlighted_code.nil?
					@code = @script_version.rewritten_code
				end
				@canonical_params = [:script_id, :version]
			}
			format.js {
				redirect_to @script.code_url
			}
			format.user_script_meta {
				redirect_to script_meta_js_path(params.merge({:script_id => params[:script_id], :name => @script.name, :format => nil}))
			}
		end
	end

	def feedback
		@script, @script_version = versionned_script(params[:script_id], params[:version])
		return if redirect_to_slug(@script, :script_id)
		@bots = 'noindex' if !params[:version].nil?
		@canonical_params = [:script_id, :version]
	end

	def user_js
		script, script_version = versionned_script(params[:script_id], params[:version])
		respond_to do |format|
			format.any(:html, :all, :js) {
				render :text => script.script_delete_type_id == 2 ? script_version.get_blanked_code : script_version.rewritten_code, :content_type => 'text/javascript'
			}
			format.user_script_meta { 
				render :text => script.script_delete_type_id == 2 ? script_version.get_blanked_code : script_version.get_rewritten_meta_block, :content_type => 'text/x-userscript-meta'
			}
		end
	end

	def meta_js
		script, script_version = versionned_script(params[:script_id], params[:version])
		render :text => script.script_delete_type_id == 2 ? script_version.get_blanked_code : script_version.get_rewritten_meta_block, :content_type => 'text/x-userscript-meta'
	end

	def install_ping
		# verify for CSRF, but do it in a way that avoids an exception. Prevents monitoring from going nuts.
		if !verified_request?
			render :nothing => true, :status => 422
			return
		end
		# ditto above, but for IP spoofing
		ip = nil
		begin
			ip = request.remote_ip
		rescue ActionDispatch::RemoteIp::IpSpoofAttackError => ex
			render :nothing => true, :status => 422
			return
		end
		# strip the slug
		Script.record_install(params[:script_id].to_i.to_s, ip)
		render :nothing => true, :status => 204
	end

	def diff
		@script = Script.find(params[:script_id])
		return if redirect_to_slug(@script, :script_id)
		versions = [params[:v1].to_i, params[:v2].to_i]

app/helpers/scripts_helper.rb
module ScriptsHelper

	def script_list_link(label, sort = nil, site = nil, set = nil)
		is_link = true
		is_search = action_name == 'search'
		is_minified = action_name == 'minified'
		is_code_search = action_name == 'code_search'
		if sort == params[:sort] and (is_search or site == params[:site]) and ((set.nil? and params[:set].nil?) or set.to_s == params[:set])
			l = label
			is_link = false
		elsif is_search
			l = link_to label, search_scripts_path(:sort => sort, :q => params[:q], :set => set)
		elsif is_minified
			l = link_to label, minified_scripts_path(:sort => sort)
		elsif is_code_search
			l = link_to label, code_search_scripts_path(:sort => sort, :c => params[:c])
		elsif site.nil?
			l = link_to label, {:sort => sort, :set => set, :site => nil}
		elsif params[:controller] == 'users'
			l = link_to label, {:sort => sort, :site => site, :set => set}
		else
			l = link_to label, by_site_scripts_path(:sort => sort, :site => site, :set => set)
		end
		return ("<li class=\"list-option#{is_link ? '' : ' list-current'}\">" + l + '</li>').html_safe
	end

	def script_applies_to_list_contents(script, by_sites)
		sats_with_domains, sats_without_domains = script.script_applies_tos.partition{|sat|sat.domain}
		return (
		sats_with_domains.map{ |sat|			
			content_for_script_applies_to_that_has_domain(sat, count_of_other_scripts_with_sat(sat, script, by_sites))
		} +
		sats_without_domains.map{ |sat| content_tag(:code, sat.text) }
		)
	end

private

	def content_for_script_applies_to_that_has_domain(sat, count_of_other_scripts)
		if count_of_other_scripts > 0
			title = t('scripts.applies_to_link_title', {:count => count_of_other_scripts, :site => sat.text})
			return link_to(sat.text, by_site_scripts_path(:site => sat.text), {:title => title})
		end
		return sat.text
	end

	def count_of_other_scripts_with_sat(script_applies_to, script, by_sites)
		return 0 if by_sites[script_applies_to.text].nil?
		# take this one out of the count if it's a listable
		return (by_sites[script_applies_to.text][:scripts] - (script.listable? ? 1 : 0))
	end

end

app/views/scripts/delete.html.erb
<%- title "Delete #{@script.name}" %>

<% moderator_view = current_user.moderator? && current_user != @script.user %>
<%=form_tag(script_do_delete_path) do |f|%>
	<p>
		<% ScriptDeleteType.all.each do |sdt| %>
			<input type="radio" required id="script_delete_type_id_<%=sdt.id%>" name="script_delete_type_id" value="<%=sdt.id%>" <%if sdt.id == 2 and moderator_view%>checked<%end%>> <label for="script_delete_type_id_<%=sdt.id%>"><%=sdt.description%></label><br>
		<% end %>
	</p>
	<% if moderator_view %>
		<p>
			<label for="reason">Why are you deleting this?</label><br>
			<textarea id="reason" name="reason" rows="5" cols="100" maxlength="500" required></textarea>
		</p>
		<p>
			<label for="locked">Lock the script to prevent undelete by the author?</label> <input type="checkbox" id="locked" name="locked" value="1" checked>
		</p>
		<% if @script.user.banned %>
			<p>(User already banned.)</p>
		<% else %>
			<p>
				<label for="banned">Ban this user?</label> <input type="checkbox" id="banned" name="banned" value="1">
			</p>
		<% end %>
		<p>This user has <%=link_to("#{@other_scripts} other non-locked scripts", @script.user)%>.</p>
	<% end %>
	<input type="submit" value="Delete">
<% end %>

app/views/scripts/index.html.erb
<%- title @title %>
<%- description @description %>

<%= render partial: 'list_options', :locals => {:by_sites => @by_sites, :scripts => @scripts}%>

<% if defined?(@set) and !@set.nil? %>
	<h3>
		<%=@set.display_name%> by <%=link_to @set.user.name, @set.user%>
		<% if user_signed_in? and current_user == @set.user%>
			<%=link_to('Edit', edit_user_script_set_path(current_user, @set))%>
		<% end %>
	</h3>
	<% if !@set.favorite %>
		<p><%=@set.description%></p>
	<% end %>
<% end %>

<% if @scripts.empty? %>
	<p><%=t('scripts.listing_no_scripts')%></p>
<% else %>
	<ol id="browse-script-list" class="script-list">
		<%= render partial: 'script', collection: @scripts %>
	</ol>
<% end %>

<% if !defined?(@paginate) or @paginate %>
	<%= will_paginate @scripts %>
<% end %>

<p><%=link_to t('scripts.new'), new_script_version_path %></p>

app/views/scripts/show.html.erb
<%- title @script.name(I18n.locale) %>
<%- description @script.description(I18n.locale) %>

<% if @script.active? 
	case @script.script_type_id
		when 1, 2 %>
			<div id="install-area">
				<%=link_to t('scripts.install'), params[:version].nil? ? script_user_js_path(@script, :name => @script.url_name) : script_user_js_path(@script, :version => params[:version], :name => @script.url_name) + '&d=.user.js', {:class => 'install-link', 'data-ping-url' => script_install_ping_path(@script, :authenticity_token => session[:_csrf_token]), 'data-is-previous-version' => !params[:version].nil?, :rel => 'nofollow'}%><%=link_to t('scripts.install_help'), help_installing_user_scripts_path, {:class => 'install-help-link', :title => t('scripts.install_help_title'), :rel => 'nofollow'}%>

				<% if user_signed_in?
					sets_direct_inclusion = []
					sets_direct_exclusion = []
					sets_indirect_inclusion = []
					sets_not_included = []
					current_user.script_sets.each do |set|
						if set.child_script_inclusions.include?(@script)
							sets_direct_inclusion << set
							next
						end
						if set.child_script_exclusions.include?(@script)
							sets_direct_exclusion << set
							next
						end
						set_script_ids = Rails.cache.fetch(set) do
							set.scripts.map{|s| s.id}
						end
						if set_script_ids.include?(@script.id)
							sets_indirect_inclusion << set
						else
							sets_not_included << set
						end
					end
					in_sets = sets_direct_inclusion + sets_indirect_inclusion
					user_has_favorites_set = current_user.script_sets.find{|s| s.favorite}
					%>
					<%=form_tag(add_to_script_set_path, {:class => 'script-in-sets'}) do |f| %>
						<% if in_sets.empty? %>
							<%=t('scripts.sets_label_no_sets')%>
						<% else %>
							<%=t('scripts.sets_label')%>
							<%=ScriptSet.favorites_first(in_sets).map{|s| link_to(s.display_name, scripts_path(:set => s.id)).html_safe}.join(', ').html_safe%>
						<% end %>
						<select name="action-set">
							<% if !user_has_favorites_set %>
								<option value="ai-fav"><%=t('scripts.sets_add_inclusion', :set_name => t('script_sets.favorites_name'))%></option>
							<% end %>
							<% ScriptSet.favorites_first(sets_direct_inclusion).each do |set| %>
								<option value="ri-<%=set.id%>"><%=t('scripts.sets_remove_inclusion', :set_name => set.display_name)%></option>
							<% end
							sets_direct_exclusion.each do |set| %>
								<option value="re-<%=set.id%>"><%=t('scripts.sets_remove_exclusion', :set_name => set.display_name)%></option>
							<% end
							sets_indirect_inclusion.each do |set| %>
								<option value="ae-<%=set.id%>"><%=t('scripts.sets_add_exclusion', :set_name => set.display_name)%></option>
							<% end
							ScriptSet.favorites_first(sets_not_included).each do |set| %>
								<option value="ai-<%=set.id%>"><%=t('scripts.sets_add_inclusion', :set_name => set.display_name)%></option>
							<% end %>
						</select>
						<input type="hidden" name="script_id" value="<%=@script.id%>">
						<input type="submit" value="→">
					<% end %>
				<% end %>
			</div>

		<% when 3 %>
			<p>
				<% if params[:version].nil?
					library_code_snippet = "<code>// @require #{script_library_js_path(@script, :version => @script_version.id, :name => @script.url_name, :only_path => false)}</code>"
				else
					library_code_snippet = "<code>// @require #{script_library_js_path(@script, :version => params[:version], :name => @script.url_name, :only_path => false)}</code>"
				end %>
				<%=t('scripts.library_instructions_html', :code => library_code_snippet.html_safe)%>
			</p>
	<% end %>
<% elsif @script.deleted? %>
	<p><%=t('scripts.deleted_notice')%>	<% if !@script.delete_reason.nil? %><%=@script.delete_reason%><%end%></p>
<% elsif !params[:version].nil? %>
	<p id="under-review-notice"><%=t('scripts.inactive_pending_changes_for_previous_version')%></p>
<% else %>
	<p id="under-review-notice"><%=t('scripts.inactive_pending_changes')%></p>
<% end %>

<div id="script-meta">
	<dl id="script-stats">
		<dt class="script-show-version"><span><%=t('scripts.version_number')%></span></dt>
		<dd class="script-show-version"><span><%=@script_version.version%></span></dd>
		<dt class="script-show-author"><span><%=t('scripts.author_name')%></span></dt>
		<dd class="script-show-author"><span><%=link_to @script.user.name, @script.user%></span></dd>
		<% if @script.script_type_id != 3 and params[:version].nil? %>
		<dt class="script-show-daily-installs"><span><%=t('scripts.daily_installs')%></span></dt>
		<dd class="script-show-daily-installs"><span><%=number_with_delimiter(@script.daily_installs)%></span></dd>
		<dt class="script-show-total-installs"><span><%=t('scripts.total_installs')%></span></dt>
		<dd class="script-show-total-installs"><span><%=number_with_delimiter(@script.total_installs)%></span></dd>
		<% end %>
		<dt class="script-list-fan-score" title="<%=t('scripts.fan_score_explanation')%>"><span><%=t('scripts.fan_score')%></span></dt>
		<dd class="script-list-fan-score"><span><%=number_with_delimiter(@script.fan_score)%></span></dd>
		<dt class="script-show-created-date"><span><%=t('scripts.created_date')%></span></dt>
		<dd class="script-show-created-date"><span><%=markup_date(@script.created_at)%></span></dd>
		<dt class="script-show-updated-date"><span><%=t('scripts.updated_date')%></span></dt>
		<dd class="script-show-updated-date"><span><%=markup_date(@script.code_updated_at)%></span></dd>
		<dt class="script-show-license"><span><%=t('scripts.license')%></span></dt>
		<dd class="script-show-license"><span><%=@script.license_display%></span></dd>
	</dl>
	<dl id="script-applies-to">
		<dt class="script-show-applies-to"><span><%=t('scripts.applies_to')%></span></dt>
		<dd class="script-show-applies-to">
			<% if @script.script_applies_tos.empty? %>
				<%=t('scripts.applies_to_all')%>
			<% else %>
				<ul class="inline-list">
					<% script_applies_to_list_contents(@script, @by_sites).each do |script_applies_to_content| %>
						<li><%=script_applies_to_content%></li>
					<% end %>
				</ul>
			<% end %>
		</dd>
	</dl>
</div>

<% localized_additional_info = @script.localized_attribute_for('additional_info', I18n.locale)
if !localized_additional_info.nil? %>
	<div id="additional-info">
		<h3><%=t('scripts.additional_info')%></h3>
		<div>
			<%=format_user_text(localized_additional_info.attribute_value, localized_additional_info.value_markup)%>
		</div>
	</div>
<% end %>

app/views/scripts/under_assessment.html.erb
<h1>Scripts including disallowed external scripts</h1>
<p><%=link_to 'Read Greasy Fork\'s policy on external scripts.', help_external_scripts_path%></p>
<% if @scripts.empty? %>
	<p>No scripts currently under assessment.</p>
<% else %>
	<ul>
		<% @scripts.each do |script| %>
			<li>
				<%=link_to script.name(I18n.locale), script %> <%=script.assessments.map{|a| a.assessment_reason.name + ' ' + a.details}.join(', ')%>
			</li>
		<% end %>
	</ul>
<% end %>