config/routes.rb
Greasyfork::Application.routes.draw do

	scope "(:locale)", locale: /de|en|es|fr|fr\-CA|id|it|ja|nl|pl|pt-BR|ru|zh\-CN|zh\-TW/ do

		get '/users', :to => 'users#index', :as => 'users'
		get '/users/webhook-info', :to => 'users#webhook_info', :as => 'user_webhook_info'
		post 'users/webhook-info', :to => 'users#webhook_info'
		get '/users/edit_sign_in' => 'users#edit_sign_in', :as => 'user_edit_sign_in'
		delete '/users/identities' => 'users#delete_identity', :as => 'user_delete_identity'
		put '/users/identities' => 'users#update_identity', :as => 'user_update_identity'
		put '/users/remove_password' => 'users#remove_password', :as => 'user_remove_password'
		put '/users/update_password' => 'users#update_password', :as => 'user_update_password'

		get '/external_login', :as => 'external_login', to: 'home#external_login'

		devise_for :users, :skip => :registrations, :controllers => { :sessions => "sessions" }
		devise_scope :user do
			resource :registration,
			only: [:new, :create, :edit, :update],
			path: 'users',
			path_names: { new: 'sign_up' },
			controller: :registrations,
			as: :user_registration do
				get :cancel
			end
		end
		devise_scope :user do
			get '/users/sign_out' => 'sessions#destroy'
			get '/auth/:provider/callback', to: 'sessions#omniauth_callback', :as => 'omniauth_callback'
			post '/auth/:provider/callback', to: 'sessions#omniauth_callback'
			get '/auth/failure', to: 'sessions#omniauth_failure'
			get '/auth/failure2', to: 'sessions#omniauth_failure'
			post '/auth/name_conflict', to: 'sessions#name_conflict'
		end

		root :to => "home#index"

		get 'scripts/sync_additional_info_form', :to => 'scripts#sync_additional_info_form', :as => 'script_sync_additional_info_form'
		resources :scripts, :only => [:index, :show] do
			get 'code.meta.js', :to => 'scripts#meta_js', :locale => nil
			get 'code.user.js', :to => 'scripts#user_js', :locale => nil

			get 'code/:name.user.js', :to => 'scripts#user_js', :as =>  'user_js', :locale => nil
			get 'code/:name.js', :to => 'scripts#user_js', :as =>  'library_js', :locale => nil
			get 'code/:name.meta.js', :to => 'scripts#meta_js', :as =>  'meta_js', :locale => nil
			match 'code/:name.meta.js', :to => 'scripts#meta_js', :locale => nil, :via => :options
			get 'code(.:format)', :to => 'scripts#show_code', :as =>  'show_code', :constraints => {:format => /.*/}
			get 'feedback(.:format)', :to => 'scripts#feedback', :as =>  'feedback'
			get 'sync(.:format)', :to => 'scripts#sync', :as =>  'sync'
			patch 'sync_update(.:format)', :to => 'scripts#sync_update', :as =>  'sync_update'
			post 'install-ping', :to => 'scripts#install_ping', :as => 'install_ping', :locale => nil
			get 'diff', :to => 'scripts#diff', :as => 'diff', :constraints => lambda{ |req| !req.params[:v1].blank? and !req.params[:v2].blank? }
			get 'delete(.:format)', :to => 'scripts#delete', :as => 'delete'
			post 'delete(.:format)', :to => 'scripts#do_delete', :as => 'do_delete'
			get 'undelete(.:format)', :to => 'scripts#undelete', :as => 'undelete'
			post 'undelete(.:format)', :to => 'scripts#do_undelete', :as => 'do_undelete'
			get 'stats(.:format)', :to => 'scripts#stats', :as => 'stats'
			get 'derivatives', :as => 'derivatives'
			collection do
				get 'by-site(.:format)', :action => 'by_site', :as => 'site_list'
				get 'by-site/:site(.:format)', :action => 'index', :as => 'by_site', :constraints => {:site => /.*/}
				get 'under-assessment(.:format)', :action => 'under_assessment', :as => 'under_assessment'
				get 'reported(.:format)', :action => 'reported', :as => 'reported'
				get 'libraries(.:format)', :action => 'libraries', :as => 'libraries'
				get 'search(.:format)', :action => 'search', :as => 'search'
				get 'minified(.:format)', :action => 'minified', :as => 'minified'
				get 'code-search(.:format)', :action => 'code_search', :as => 'code_search'
			end
			resources :script_versions, :only => [:create, :new, :show, :index], :path => 'versions'
		end
		resources :script_versions, :only => [:create, :new]
		get 'script_versions/additional_info_form', :to => 'script_versions#additional_info_form', :as => 'script_version_additional_info_form'
		resources :users, :only => :show do
			post 'webhook'
			resources :script_sets, :only => [:create, :new, :edit, :update, :destroy], :path => 'sets'
		end
		post 'script_sets/add_to_set', :to => 'script_sets#add_to_set', :as => 'add_to_script_set'

		get 'import', :to => 'import#index', :as => 'import_start'
		get 'import/userscriptsorg', :to => 'import#userscriptsorg', :as => 'import_userscriptsorg'
		post 'import/verify', :to => 'import#verify', :as => 'import_verify'
		post 'import/add', :to => 'import#add', :as => 'import_add'
		get 'import/url', :to => 'import#url', :as => 'import_url'

		get 'help', :to => 'help#index', :as => 'help'
		get 'help/allowed-markup', :to => 'help#allowed_markup', :as => 'help_allowed_markup'
		get 'help/code-rules', :to => 'help#code_rules', :as => 'help_code_rules'
		get 'help/contact', :to => 'help#contact', :as => 'help_contact'
		get 'help/credits', :to => 'help#credits', :as => 'help_credits'
		get 'help/disallowed-code', :to => 'help#disallowed_code', :as => 'help_disallowed_code'
		get 'help/external-scripts', :to => 'help#external_scripts', :as => 'help_external_scripts'
		get 'help/installing-user-scripts', :to => 'help#installing_user_scripts', :as => 'help_installing_user_scripts'
		get 'help/rewriting', :to => 'help#rewriting', :as => 'help_rewriting'
		get 'help/meta-keys', :to => 'help#meta_keys', :as => 'help_meta_keys'

		post 'preview-markup', :to => 'home#preview_markup', :as => 'preview_markup'

		resources :moderator_actions, :only => [:index]

	end

	get 'sso', :to => 'home#sso'
end

app/models/user.rb
require 'securerandom'

class User < ActiveRecord::Base

	has_many :scripts
	has_many :listable_scripts, -> {
		# copy from Script.listable. Is this the most elegant way to do this?
		o = nil
		Script.listable.where_values.each{|wv| o = o.nil? ? where(wv) : o.where(wv)}
		o
	}, :class_name => 'Script'

	#this results in a cartesian join when included with the scripts relation
	#has_many :discussions, through: :scripts

	has_and_belongs_to_many :roles

	has_many :identities

	has_many :script_sets

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

	validates_presence_of :name, :profile_markup
	validates_uniqueness_of :name
	validates_length_of :profile, :maximum => 10000
	validates_inclusion_of :profile_markup, :in => ['html', 'markdown']

	strip_attributes

	def discussions_on_scripts_written
		scripts.map {|s| s.discussions}.flatten.sort{|a,b| a.updated <=> b.updated }
	end

	def slugify(name)
		# take out swears
		r = name.downcase.gsub(/motherfucking|motherfucker|fucking|fucker|fucks|fuck|shitty|shits|shit|niggers|nigger|cunts|cunt/, '')
		# multiple non-alphas into one
		r.gsub!(/([^[:alnum:]])[^[:alnum:]]+/) {|s| $1}
		# leading non-alphas
		r.gsub!(/^[^[:alnum:]]+/, '')
		# trailing non-alphas
		r.gsub!(/[^[:alnum:]]+$/, '')
		# non-alphas into dashes
		r.gsub!(/[^[:alnum:]]/, '-')
		# use "script" if we don't have something suitable
		r = 'user' if r.empty?
		return r
	end

	def to_param
		"#{id}-#{slugify(name)}"
	end

	def moderator?
		!roles.select { |role| role.name == 'Moderator' }.empty?
	end

	def administrator?
		!roles.select { |role| role.name == 'Moderator' }.empty?
	end

	def generate_webhook_secret
		self.webhook_secret = SecureRandom.hex(64)
	end

	def pretty_signin_methods
		return self.identity_providers_used.map{|p| Identity.pretty_provider(p)}
	end

	def identity_providers_used
		return self.identities.map{|i| i.provider}.uniq
	end

	def favorite_script_set
		return ScriptSet.where(:favorite => true).where(:user_id => id).first
	end

	def serializable_hash(options = nil)
		h = super({ only: [:id, :name] }.merge(options || {})).merge({
			:url => Rails.application.routes.url_helpers.user_path(nil, self, {:only_path => false})
		})
		# rename listable_scripts to scripts
		if !h['listable_scripts'].nil?
			h['scripts'] = h['listable_scripts']
			h.delete('listable_scripts')
		end
		return h
	end

	protected

	def password_required?
		self.new_record? && self.identities.empty?
	end
end

app/controllers/users_controller.rb
require 'script_importer/script_syncer'

class UsersController < ApplicationController

	skip_before_action :verify_authenticity_token, :only => [:webhook]

	before_filter :authenticate_user!, :except => [:show, :webhook, :index]

	HMAC_DIGEST = OpenSSL::Digest::Digest.new('sha1')

	def index
		@users = User.includes(:listable_scripts).references(:scripts).group('users.id').order(self.class.get_sort(params)).paginate(:page => params[:page], :per_page => get_per_page)
	end

	def show
		# TODO sort scripts by name, keeping into account localization
		@user = User.order('scripts.default_name')
		# current user will display discussions
		if !current_user.nil? and current_user.id == params[:id].to_i
			@user = @user.includes(:scripts => [:discussions, :script_type, :script_delete_type, :localized_attributes => :locale])
		else
			@user = @user.includes(:scripts => [:script_type, :script_delete_type, :localized_attributes => :locale])
		end
		@user = @user.find(params[:id])

		return if redirect_to_slug(@user, :id)

		respond_to do |format|
			format.html {
				@by_sites = ScriptsController.get_top_by_sites

				@scripts = ((!current_user.nil? && current_user.id == @user.id) or (!current_user.nil? and current_user.moderator?)) ? @user.scripts : @user.scripts.listable
				@user_has_scripts = !@scripts.empty?
				@scripts = ScriptsController.apply_filters(@scripts, params)

				@bots = 'noindex,follow' if !params[:sort].nil?

				@link_alternates = [
					{:url => url_for(params.merge({:only_path => true, :format => :json})), :type => 'application/json'},
					{:url => url_for(params.merge({:only_path => true, :format => :jsonp, :callback => 'callback'})), :type => 'application/javascript'}
				]
				@canonical_params = [:id, :page, :per_page, :set, :site, :sort]
			}
			format.json { render :json => @user.as_json(:include => :listable_scripts) }
			format.jsonp { render :json => @user.as_json(:include => :listable_scripts), :callback => clean_json_callback_param }
		end
	end

	def webhook_info
		@user = current_user
		if request.post?
			@user.generate_webhook_secret
			@user.save!
		end
		@github_scripts = Script.not_deleted.where(:user_id => @user.id).where('sync_identifier LIKE "https://github.com/%" OR sync_identifier LIKE "https://raw.githubusercontent.com/%"').includes(:script_sync_type)
	end

	def webhook
		user = User.find(params[:user_id])

		# using the secret, see if this is good
		body = request.body.read
		if user.webhook_secret.nil? or request.headers['X-Hub-Signature'] != ('sha1=' + OpenSSL::HMAC.hexdigest(HMAC_DIGEST, user.webhook_secret, body))
			render :nothing => true, :status => 403
			return
		end

		if request.headers['X-GitHub-Event'] == 'ping'
			render :json => {:message => 'Webhook successfully configured.'}
			return
		end

		if request.headers['X-GitHub-Event'] != 'push'
			render :nothing => true, :status => 406
		end

		# construct the raw URLs from the provided info. raw URLs are in the format:
		# (repository url)/raw/(branch)/(path) OR
		# https://raw.githubusercontent.com/(user)/(repo)/(branch)/(path)
		base_paths = [
			params[:repository][:url] + '/raw/' + params[:ref].split('/').last + '/', 'https://raw.githubusercontent.com/' + params[:repository][:url].split('/')[3..4].join('/') + '/' + params[:ref].split('/').last + '/'
		]
		logger.error(base_paths.inspect)
		changed_urls = {}
		params[:commits].each do |c|
			# there's also "added" and "deleted", but I don't think there's a case for syncing when those happen
			# rails seems to set modified to nil instead of empty
			if !c[:modified].nil?
				c[:modified].each do |m|
					base_paths.each do |bp|
						url = bp + m
						if !changed_urls.has_key?(url)
							changed_urls[url] = []
						end
						changed_urls[url] << c[:message]
					end
				end
			end
		end

		changed_script_urls = []
		if !changed_urls.empty?
			# find the scripts syncing from those URLs
			scripts = Script.not_deleted.where(:user_id => user.id).where(:sync_identifier => changed_urls.keys).includes(:script_sync_type)

			# trigger sync on each
			scripts.each do |s|
				changed_script_urls << script_url(s, :only_path => false)
				# update sync type to webhook, now that we know this script is affected by it
				if s.script_sync_type_id != 3
					s.script_sync_type_id = 3
					s.save(:validate => false)
				end
				# sync
				# GitHub's raw server caches things for up to 5 minutes. We also want to let the webhook request complete asynchronously anyway.
				ScriptImporter::ScriptSyncer.delay(run_at: 5.minutes.from_now).sync(s, 'Synced from GitHub - ' + changed_urls[s.sync_identifier].join(' '))
			end
		end

		render :json => {:affected_scripts => changed_script_urls}
	end

	def edit_sign_in
	end

	def update_password
		current_user.password = params[:password]
		current_user.password_confirmation = params[:password_confirmation]
		# prevent empty and invalid passwords
		if !current_user.valid? or params[:password].nil? or params[:password].empty?
			current_user.reload
			render :edit_sign_in
			return
		end
		current_user.save!
		# password changed, have to sign in again
		sign_in current_user, :bypass => true
		flash[:notice] = t('users.password_updated')
		redirect_to user_edit_sign_in_path
	end

	def remove_password
		if current_user.identities.empty?
			flash[:notice] = t('users.cant_remove_password')
			redirect_to user_edit_sign_in_path
			return
		end
		current_user.encrypted_password = nil
		current_user.save!
		# password changed, have to sign in again
		sign_in current_user, :bypass => true
		flash[:notice] = t('users.password_removed')
		redirect_to user_edit_sign_in_path
	end

	def update_identity
		current_user.identities.each do |id|
			if id.provider == params[:provider]
				flash[:notice] = t('users.external_sign_in_updated', :provider => Identity.pretty_provider(id.provider))
				id.syncing = params[:syncing]
				id.save
			end
		end
		redirect_to user_edit_sign_in_path
	end

	def delete_identity
		if current_user.identities.size == 1 and current_user.encrypted_password.nil?
			flash[:notice] = t('users.cant_remove_sign_in', :provider => Identity.pretty_provider(params[:provider]))
			redirect_to user_edit_sign_in_path
			return
		end
		current_user.identities.each do |id|
			if id.provider == params[:provider]
				flash[:notice] = t('users.external_sign_in_removed', :provider => Identity.pretty_provider(id.provider))
				id.delete
			end
		end
		redirect_to user_edit_sign_in_path
	end

private

	def self.get_sort(params)
		case params[:sort]
			when 'scripts'
				return "count(scripts.id) DESC, users.id"
			when 'total_installs'
				return "sum(scripts.total_installs) DESC, users.id"
			when 'created_script'
				return "max(scripts.created_at) DESC, users.id"
			when 'updated_script'
				return "max(scripts.code_updated_at) DESC, users.id"
			when 'daily_installs'
				return "sum(scripts.daily_installs) DESC, users.id"
			when 'fans'
				return "sum(scripts.fan_score) DESC, users.id"
			when 'name'
				return "users.name ASC, users.id"
			else
				params[:sort] = nil
				return "users.created_at DESC, users.id"
		end
	end

end

app/helpers/users_helper.rb
module UsersHelper

	def user_list_link(label, sort = nil)
		is_link = false
		if sort != params[:sort]
			is_link = true
			label = link_to label, users_path(:sort => sort)
		end
		return ("<li class=\"list-option#{is_link ? '' : ' list-current'}\">" + label + '</li>').html_safe
	end

end

app/views/users/_user.html.erb
<li><%=t('users.list_display_html', {:user_link => link_to(user.name, user), :count => user.listable_scripts.count})%></li>

app/views/users/edit_sign_in.html.erb
<%- title t('users.edit_sign_in_title') %>

<script src="https://login.persona.org/include.js" type="text/javascript"></script>

<h3><%=t('users.edit_sign_in_password')%></h3>

<% if !current_user.errors.empty? %>
	<%=t('common.error_preamble')%>
	<ul>
		<% current_user.errors.full_messages.each do |msg| %>
			<li><%=msg%></li>
		<% end %>
	</ul>
<% end %>

<% if current_user.encrypted_password.nil? %>
	<p><%=t('users.no_password_set_info')%></p>
<% end %>

<%=form_tag(user_update_password_path, :method => :put) do |f|%>

	<div><%= label_tag t('activerecord.attributes.user.password') %><br>
	<%= password_field_tag :password, nil, :autocomplete => "off", :required => true %></div>

	<% # this is provided in an updated devise-i18n-views %>
	<div><%= label_tag t('activerecord.attributes.user.password_confirmation', :default => 'Password confirmation') %><br />
	<%= password_field_tag :password_confirmation, nil, :required => true %></div>

	<% if current_user.encrypted_password.nil? %>
		<div><%= submit_tag t('users.set_password') %></div>
	<% else %>
		<div><%= submit_tag t('users.update_password') %></div>
	<% end %>
<% end %>

<% if !current_user.encrypted_password.nil? and !current_user.identities.empty? %>
	<%=form_tag(user_remove_password_path, :method => :put, :class => 'inline-form') do |f|%>
		<p><%=t('users.remove_password_info')%> <input type="submit" value="<%=t('users.remove_password')%>"></p>
	<% end %>
<% end %>

<h3><%=t('users.edit_sign_in_external')%></h3>

<% if current_user.identities.empty? %>
	<p><%=t('users.external_sign_in_info_no_sign_ins')%></p>
<% else %>
	<p><%=t('users.external_sign_in_info_with_sign_ins')%></p>
	<ul>
		<% current_user.identities.each do |id| %>
			<li>
				<% if !id.url.nil? %>
					<%=link_to id.pretty_provider, id.url%>
				<% else %>
					<%=id.pretty_provider%>
				<% end %>
				<% if id.syncing %>
					<%=t('users.syncing_indicator')%>
					<%=form_tag(user_update_identity_path, :method => :put, :class => 'inline-form') do |f|%>
						<input type="hidden" name="provider" value="<%=id.provider%>">
						<input type="hidden" name="syncing" value="0">
						<input type="Submit" value="<%=t('users.disable_syncing')%>">
					<% end %>
				<% else %>
					<%=form_tag(user_update_identity_path, :method => :put, :class => 'inline-form') do |f|%>
						<input type="hidden" name="provider" value="<%=id.provider%>">
						<input type="hidden" name="syncing" value="1">
						<input type="Submit" value="<%=t('users.enable_syncing')%>">
					<% end %>
				<% end %>
				<% if current_user.identities.size > 1 or !current_user.encrypted_password.nil? %>
					<%=form_tag(user_delete_identity_path, :method => :delete, :class => 'inline-form') do |f|%>
						<input type="hidden" name="provider" value="<%=id.provider%>">
						<input type="Submit" value="<%=t('users.remove_external_sign_in')%>">
					<% end %>
				<% end %>
			</li>
		<% end %>
	</ul>
<% end %>

<% available_providers = (Rails.application.config.available_auths.keys - current_user.identity_providers_used) %>
<% if !available_providers.empty? %>
	<p><%=t('users.add_external_sign_in_info')%></p>
	<ul>
		<% available_providers.each do |provider| %>
			<li><%=link_to Identity.pretty_provider(provider), "/auth/#{provider}", {:class => "#{provider}-login", 'data-return-to' => url_for()}%></li>
		<% end %>
	</ul>
<% end %>

app/views/users/show.html.erb
<%- title @user.name %>
<%- description "Greasy Fork profile for #{@user.name}" %>

<h2><%=@user.name%></h2>

<% if !@user.profile.nil? %>
	<section id="user-profile"><%=format_user_text(@user.profile, @user.profile_markup)%></section>
<% end %>

<% same_user = !current_user.nil? && current_user.id == @user.id
if same_user %>
	<section id="control-panel">
		<header>
			<h3><%=t('users.control_panel')%></h3>
		</header>
		<ul id="user-control-panel">
			<li><%= link_to t('scripts.new'), new_script_version_path%></li>
			<li><%= link_to 'New script set', new_user_script_set_path(@user)%></li>
			<li><%= link_to t('scripts.import'), import_start_path%></li>
			<li><%= link_to t('users.set_up_webhook'), user_webhook_info_path%></li>
			<li><%= link_to t('users.edit'), edit_user_registration_path%></li>
			<li><%= link_to t('users.edit_sign_in'), user_edit_sign_in_path%></li>
			<li><%= link_to t('users.sign_out'), destroy_user_session_path, :method => :delete %></li>
		</ul>
	</section>

	<% if @user.moderator? %>
		<section id="moderator-actions">
			<header>
				<h3>Moderator actions</h3>
			</header>
			<ul>
				<li><%=link_to "Reported scripts: #{Script.reported.count}", reported_scripts_path%></li>
				<li><%=link_to "Possibly minified", minified_scripts_path%></li>
				<% if @user.administrator? %>
					<li><%=link_to "Under assessment: #{Script.under_assessment.count}", under_assessment_scripts_path%></li>
					<li><%=Script.connection.select_value('SELECT COUNT(*) FROM delayed_jobs WHERE last_error IS NULL')%> delayed_jobs pending, <%=Script.connection.select_value('SELECT COUNT(*) FROM delayed_jobs WHERE last_error IS NOT NULL')%> failed.</li>
					<li>Last duplicate check: <%=CpdDuplication.first.nil? ? 'never' : markup_date(CpdDuplication.first.created_at)%></li>
				<% end %>
			</ul>
		</section>
	<% end %>

	<% if !@user.scripts.empty? 
		dosr = @user.discussions_on_scripts_written %>
		<section id="user-discussions-on-scripts-written">
			<header>
				<h3><%=t('users.discussions_on_scripts')%> <a href="/forum/discussions/feed.rss?script_author=<%=@user.id%>"><img src="<%=asset_path('feed-icon-14x14.png')%>" alt="<%=t('users.discussions_on_scripts_feed_alt')%>" rel="nofollow"></a></h3>
			</header>
			<% if dosr.empty? %>
				<p><%=t('users.discussions_on_scripts_none')%></p>
			<% else %>
				<ul class="discussion-list">
					<% dosr.reverse.take(10).each do |d| %>
						<li class="<%=discussion_class(d)%>">
							<%= render :partial => 'forum_discussions/discussion', :locals => {:discussion => d, :show_script => true}%>
						</li>
					<% end 
					if dosr.length > 10 %>
						<li class="more-discussions"><a href="/forum/?script_author=<%=@user.id%>" rel="nofollow"><%=t('users.discussions_on_scripts_more')%></a></li>
					<% end %>
				</ul>
			<% end %>
		</section>
	<% end %>
<% end %>

<% if !@user.script_sets.empty? or same_user %>
	<section>
		<header>
			<h3>Script Sets</h3>
		</header>
		<ul id="user-script-sets">
			<% favorites_set = @user.script_sets.find{|ss| ss.favorite}
			if !favorites_set.nil? %>
				<li><%=t('script_sets.favorites_name')%> <%=link_to 'View scripts', scripts_path(:set => favorites_set.id)%> <% if same_user %><%=link_to 'Edit', edit_user_script_set_path(@user, favorites_set)%><% end %></li>
			<% elsif same_user %>
				<li><%=t('script_sets.favorites_name')%> <%=link_to 'Edit', new_user_script_set_path(@user, :fav =>  1)%></li>
			<% end
			@user.script_sets.select{|ss| !ss.favorite}.each do |ss| %>
				<li><%=ss.name%>: <%=ss.description%> <%=link_to 'View scripts', scripts_path(:set => ss.id)%> <% if same_user %><%=link_to 'Edit', edit_user_script_set_path(@user, ss)%><% end %></li>
			<% end %>
		</ul>
	</section>
<% end %>

<% # show deletions in a separate section if we're going to show any
deleted_script_list = @scripts.select{|s| s.deleted?}
script_list = @scripts - deleted_script_list %>
<section>
	<% if @user_has_scripts %>
		<%= render partial: 'scripts/list_options', :locals => {:by_sites => @by_sites, :scripts => script_list}%>
	<% end %>
	<header>
		<h3><%=t('users.script_list')%></h3>
	</header>
	<% if !@user_has_scripts %>
		<p><%=t('users.script_list_none')%></p>
	<% elsif script_list.empty? %>
		<p><%=t('users.script_list_none_for_filter')%></p>
	<% else %>
		<ol id="user-script-list" class="script-list">
			<%= render partial: 'scripts/script', collection: script_list %>
		</ol>
	<% end %>
</section>

<% if !deleted_script_list.empty? %>
	<section>
		<header>
			<h3><%=t('users.deleted_script_list')%></h3>
		</header>
		<ol id="user-deleted-script-list" class="script-list">
			<%= render partial: 'scripts/script', collection: deleted_script_list %>
		</ol>
	</section>
<% end %>

app/views/users/webhook_info.html.erb
<%- title "Setting up a GitHub webhook" %>
<%- description "Setting up a GitHub webook to update scripts on Greasy Fork automatically." %>

<p>A GitHub webhook connected with Greasy Fork makes it so any push to your GitHub repository automatically updates your scripts on Greasy Fork in a matter of minutes.</p>

<p>To use this feature, you must have scripts on Greasy Fork set up to sync from GitHub. You can add new scripts by <%= link_to 'importing new scripts into Greasy Fork', import_start_path%>, or you can set previously posted scripts to sync by accessing the "Sync" tab from the script's page. Here's the GitHub-syncing scripts you have so far:</p>

<% if @github_scripts.empty? %>
	<p><i>(None)</i></p>
<% else %>
	<ul>
		<% @github_scripts.each do |s| %>
			<li><%=link_to s.name, s%> - <%=s.script_sync_type.name.downcase%> syncing from <%=link_to s.sync_identifier, s.sync_identifier%></li>
		<% end %>
	</ul>
<% end %>

<p>To set up the webhook on GitHub's side, access to your GitHub repository and go to Settings, Webhooks &amp; Services, Add webhook, then enter the data below. You can set up multiple repositories with the same info.</p>
<dl>
	<dt>Payload URL</dt>
	<dd><%=user_path(@user, :only_path => false)%>/webhook</dd>
	<dt>Content type</dt>
	<dd>application/json</dd>
	<dt>Secret</dt>
	<dd>
		<%=form_tag do |f|%>
			<% if @user.webhook_secret.nil? %>
				<input type="submit" value="Generate">
			<% else %>
				<textarea cols="64" rows="2"><%=@user.webhook_secret%></textarea> <input type="submit" value="Regenerate">
			<% end %>
		<%end%>
	</dd>
	<dt>Which events would you like to trigger this webhook?</dt>
	<dd>Just the push event.</dd>
	<dt>Active</dt>
	<dd>(Checked)</dd>
</dl>

<p>After you set up the webhook, GitHub will send a ping to Greasy Fork. If this ping is successful, then you've set things up correctly. Your scripts will continue to show a sync type of "Automatic" or "Manual" until the first push happens, and then they'll be set to "Webhook".</p>