config/routes.rb
Greasyfork::Application.routes.draw do

	scope "(:locale)", locale: /de|en|es|fr|fr\-CA|id|it|ja|nl|pl|pt-BR|ru|zh\-CN|zh\-TW/ do

		get '/users', :to => 'users#index', :as => 'users'
		get '/users/webhook-info', :to => 'users#webhook_info', :as => 'user_webhook_info'
		post 'users/webhook-info', :to => 'users#webhook_info'
		get '/users/edit_sign_in' => 'users#edit_sign_in', :as => 'user_edit_sign_in'
		delete '/users/identities' => 'users#delete_identity', :as => 'user_delete_identity'
		put '/users/identities' => 'users#update_identity', :as => 'user_update_identity'
		put '/users/remove_password' => 'users#remove_password', :as => 'user_remove_password'
		put '/users/update_password' => 'users#update_password', :as => 'user_update_password'

		get '/external_login', :as => 'external_login', to: 'home#external_login'

		devise_for :users, :skip => :registrations, :controllers => { :sessions => "sessions" }
		devise_scope :user do
			resource :registration,
			only: [:new, :create, :edit, :update],
			path: 'users',
			path_names: { new: 'sign_up' },
			controller: :registrations,
			as: :user_registration do
				get :cancel
			end
		end
		devise_scope :user do
			get '/users/sign_out' => 'sessions#destroy'
			get '/auth/:provider/callback', to: 'sessions#omniauth_callback', :as => 'omniauth_callback'
			post '/auth/:provider/callback', to: 'sessions#omniauth_callback'
			get '/auth/failure', to: 'sessions#omniauth_failure'
			get '/auth/failure2', to: 'sessions#omniauth_failure'
			post '/auth/name_conflict', to: 'sessions#name_conflict'
		end

		root :to => "home#index"

		get 'scripts/sync_additional_info_form', :to => 'scripts#sync_additional_info_form', :as => 'script_sync_additional_info_form'
		resources :scripts, :only => [:index, :show] do
			get 'code.meta.js', :to => 'scripts#meta_js', :locale => nil
			get 'code.user.js', :to => 'scripts#user_js', :locale => nil

			get 'code/:name.user.js', :to => 'scripts#user_js', :as =>  'user_js', :locale => nil
			get 'code/:name.js', :to => 'scripts#user_js', :as =>  'library_js', :locale => nil
			get 'code/:name.meta.js', :to => 'scripts#meta_js', :as =>  'meta_js', :locale => nil
			match 'code/:name.meta.js', :to => 'scripts#meta_js', :locale => nil, :via => :options
			get 'code(.:format)', :to => 'scripts#show_code', :as =>  'show_code', :constraints => {:format => /.*/}
			get 'feedback(.:format)', :to => 'scripts#feedback', :as =>  'feedback'
			get 'sync(.:format)', :to => 'scripts#sync', :as =>  'sync'
			patch 'sync_update(.:format)', :to => 'scripts#sync_update', :as =>  'sync_update'
			post 'install-ping', :to => 'scripts#install_ping', :as => 'install_ping', :locale => nil
			get 'diff', :to => 'scripts#diff', :as => 'diff', :constraints => lambda{ |req| !req.params[:v1].blank? and !req.params[:v2].blank? }
			get 'delete(.:format)', :to => 'scripts#delete', :as => 'delete'
			post 'delete(.:format)', :to => 'scripts#do_delete', :as => 'do_delete'
			get 'undelete(.:format)', :to => 'scripts#undelete', :as => 'undelete'
			post 'undelete(.:format)', :to => 'scripts#do_undelete', :as => 'do_undelete'
			get 'stats(.:format)', :to => 'scripts#stats', :as => 'stats'
			get 'derivatives', :as => 'derivatives'
			collection do
				get 'by-site(.:format)', :action => 'by_site', :as => 'site_list'
				get 'by-site/:site(.:format)', :action => 'index', :as => 'by_site', :constraints => {:site => /.*/}
				get 'under-assessment(.:format)', :action => 'under_assessment', :as => 'under_assessment'
				get 'reported(.:format)', :action => 'reported', :as => 'reported'
				get 'libraries(.:format)', :action => 'libraries', :as => 'libraries'
				get 'search(.:format)', :action => 'search', :as => 'search'
				get 'minified(.:format)', :action => 'minified', :as => 'minified'
				get 'code-search(.:format)', :action => 'code_search', :as => 'code_search'
			end
			resources :script_versions, :only => [:create, :new, :show, :index], :path => 'versions'
		end
		resources :script_versions, :only => [:create, :new]
		get 'script_versions/additional_info_form', :to => 'script_versions#additional_info_form', :as => 'script_version_additional_info_form'
		resources :users, :only => :show do
			post 'webhook'
			resources :script_sets, :only => [:create, :new, :edit, :update, :destroy], :path => 'sets'
		end
		post 'script_sets/add_to_set', :to => 'script_sets#add_to_set', :as => 'add_to_script_set'

		get 'import', :to => 'import#index', :as => 'import_start'
		get 'import/userscriptsorg', :to => 'import#userscriptsorg', :as => 'import_userscriptsorg'
		post 'import/verify', :to => 'import#verify', :as => 'import_verify'
		post 'import/add', :to => 'import#add', :as => 'import_add'
		get 'import/url', :to => 'import#url', :as => 'import_url'

		get 'help', :to => 'help#index', :as => 'help'
		get 'help/allowed-markup', :to => 'help#allowed_markup', :as => 'help_allowed_markup'
		get 'help/code-rules', :to => 'help#code_rules', :as => 'help_code_rules'
		get 'help/contact', :to => 'help#contact', :as => 'help_contact'
		get 'help/credits', :to => 'help#credits', :as => 'help_credits'
		get 'help/disallowed-code', :to => 'help#disallowed_code', :as => 'help_disallowed_code'
		get 'help/external-scripts', :to => 'help#external_scripts', :as => 'help_external_scripts'
		get 'help/installing-user-scripts', :to => 'help#installing_user_scripts', :as => 'help_installing_user_scripts'
		get 'help/rewriting', :to => 'help#rewriting', :as => 'help_rewriting'
		get 'help/meta-keys', :to => 'help#meta_keys', :as => 'help_meta_keys'

		post 'preview-markup', :to => 'home#preview_markup', :as => 'preview_markup'

		resources :moderator_actions, :only => [:index]

	end

	get 'sso', :to => 'home#sso'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= content_for?(:title) ? content_for(:title) : "Greasy Fork" %></title>
	<% if content_for?(:description) %><meta name="description" value="<%=content_for(:description)%>"><% end %>
	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<% if defined?(@bots) %>
		<meta name="robots" content="<%=@bots%>">
	<% end %>
	<link rel="canonical" href="<%=url_for(params.slice(*@canonical_params).merge({:host => 'greasyfork.org', :protocol => 'https'}))%>">
	<link rel="icon" href="<%=asset_path 'blacklogo16.png'%>">
	<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
	<% if request.get?
		# https://support.google.com/webmasters/answer/189077
		Rails.configuration.available_locales.each do |code, name|
			if code == 'en' %>
				<link rel="alternate" hreflang="<%=code%>" href="<%=url_for(params.except(:locale).merge({:locale => nil, :only_path => true}))%>">
			<% else %>
				<link rel="alternate" hreflang="<%=code%>" href="<%=url_for(params.except(:locale).merge({:locale => code, :only_path => true}))%>">
			<% end
		end
	end %>
	<% if defined?(@link_alternates)
		@link_alternates.each do |la| %>
			<link rel="alternate" type="<%=la[:type]%>" href="<%=la[:url]%>" <%if !la[:title].nil?%>title="<%=la[:title]%>"<%end%>>
		<% end
	end %>
</head>
<body>

	<header id="main-header">
		<div id="site-name">
			<%=link_to_unless_current "<img src=\"#{asset_path 'blacklogo96.png'}\" alt=\"\">".html_safe, root_path%>
			<div id="site-name-text">
				<h1><%=link_to_unless_current 'Greasy Fork', root_path%></h1>
				<p class="subtitle">Neither greasy nor a fork.</p>
			</div>
		</div>
		<div id="site-nav">
			<div id="nav-user-info">
				<% if user_signed_in? %>
					<span class="user-profile-link"><%=link_to(current_user.name, current_user)%></span>
				<% else %>
					<span class="sign-in-link"><%=link_to(t('.sign_in'), new_user_session_path(request.get? ? {:return_to => request.fullpath} : {}), {:rel => 'nofollow'})%></span>
				<% end %>
				<% if request.get?
					form_action = url_for(params.except(:locale).merge({:locale => nil, :only_path => true}))
				else
					form_action = root_path({:locale => nil, :only_path => true})
				end %>
				<form id="language-selector" action="<%=form_action%>">
					<select id="language-selector-locale" name="locale">
						<% Rails.configuration.available_locales.each do |code, name|
							if request.get?
								if code == 'en' %>
									<option data-language-url="<%=url_for(params.except(:locale).merge({:locale => nil, :only_path => true}))%>" value="<%=code%>"<%if params[:locale] == code or params[:locale].nil?%> selected<%end%>><%=name%> (<%=code%>)</option>
								<% else %>
									<option data-language-url="<%=url_for(params.except(:locale).merge({:locale => code, :only_path => true}))%>" value="<%=code%>"<%if params[:locale] == code%> selected<%end%>><%=name%> (<%=code%>)</option>
								<% end
							else
								if code == 'en' %>
									<option data-language-url="<%=root_path({:locale => nil, :only_path => true})%>" value="<%=code%>"<%if params[:locale] == code or params[:locale].nil?%> selected<%end%>><%=name%> (<%=code%>)</option>
								<% else %>
									<option data-language-url="<%=root_path({:locale => code, :only_path => true})%>" value="<%=code%>"<%if params[:locale] == code%> selected<%end%>><%=name%> (<%=code%>)</option>
								<% end
							end
						end %>
						<option value="help">Help us translate!</option>
					</select><input id="language-selector-submit" type="submit" value="→">
					<script>
						/* submit is handled by js if enabled */
						document.getElementById("language-selector-submit").style.display = "none"
					</script>
				</form>
			</div>
			<nav>
				<li class="scripts-index-link"><%=link_to(t('.script_list'), scripts_path)%></li>
				<% # user signed in to main site, but not to forum?
				if user_signed_in? and cookies[:Vanilla].nil? %>
					<li class="forum-link"><%=link_to(t('.forum'), '/forum/entry/jsconnect?client_id=1462516369')%></li>
				<% else %>
					<li class="forum-link"><%=link_to(t('.forum'), '/forum/')%></li>
				<% end %>
				<li class="help-link"><%=link_to_unless_current(t('.help'), help_path)%></li>
				<li class="nav-search">
					<form id="script-search" action="<%=search_scripts_path()%>">
						<input type="search" name="q" placeholder="<%=t('.search')%>" value="<%=params[:q]%>" size="10"><input type="submit" value="→">
					</form>
				</li>
			</nav>
		</div>
	</header>

<% if !notice.nil? %>
	<p class="notice"><%=notice%></p>
<% end %>
<% if !alert.nil? %>
	<p class="alert"><%=alert%></p>
<% end %>

<%= content_for?(:content) ? yield(:content) : yield %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48197018-1', 'greasyfork.org');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/layouts/scripts.html.erb
<% content_for :content do %>
	<section id="script-info">
		<header>
			<h2><%=@script.name(I18n.locale)%></h2>
			<p><%=@script.description(I18n.locale)%></p>
			<% if !params[:version].nil?
				latest_version_link = link_to t('scripts.version_notice_latest_version_link'), {:version => nil}%>
				<p id="version-note"><%=t('scripts.version_notice_html', :date => @script.updated_at, :latest_version_link => latest_version_link.html_safe)%></p>
			<% end %>
		</header>
		<ul id="script-links">
			<li<%=current_page?(script_path(@script, :version => params[:version])) ? ' class="current"'.html_safe : ''%>><%= link_to_unless_current "<span>#{t('scripts.info_page')}</span>".html_safe, script_path(@script, :version => params[:version])%></li>
			<li<%=current_page?(script_show_code_path(@script, :version => params[:version])) ? ' class="current"'.html_safe : ''%>><%= link_to_unless_current "<span>#{t('scripts.code_page')}</span>".html_safe, script_show_code_path(@script, :version => params[:version])%></li>
			<li<%=current_page?(script_script_versions_path(@script, :version => params[:version])) ? ' class="current"'.html_safe : ''%>><%= link_to_unless_current "<span>#{t('scripts.history_page')}</span>".html_safe, script_script_versions_path(@script, :version => params[:version])%></li>
			<li<%=current_page?(script_feedback_path(@script, :version => params[:version])) ? ' class="current"'.html_safe : ''%>><%= link_to_unless_current "<span>#{t('scripts.feedback_page', :count => @script.discussions.count)}</span>".html_safe, script_feedback_path(@script, :version => params[:version])%></li>
			<li<%=current_page?(script_stats_path(@script, :version => params[:version])) ? ' class="current"'.html_safe : ''%>><%= link_to_unless_current "<span>#{t('scripts.stats_page')}</span>".html_safe, script_stats_path(@script, :version => params[:version])%></li>
			<% same_user = !current_user.nil? && current_user.id == @script.user_id
			user_is_mod = !current_user.nil? && current_user.moderator? %>
			<% if (same_user and !@script.locked) or user_is_mod %>
				<li<%=current_page?(script_derivatives_path(@script, :version => params[:version])) ? ' class="current"'.html_safe : ''%>><%= link_to_unless_current "<span>#{t('scripts.derivatives_page')}</span>".html_safe, script_derivatives_path(@script, :version => params[:version])%></li>
			<% end %>
			<% if same_user and !@script.locked %>
				<li<%=current_page?(new_script_script_version_path(@script.id)) ? ' class="current"'.html_safe : ''%>><%= link_to_unless_current "<span>#{t('scripts.update_page')}</span>".html_safe, new_script_script_version_path(@script.id)%></li>
				<li<%=current_page?(script_sync_path(@script)) ? ' class="current"'.html_safe : ''%>><%= link_to_unless_current "<span>#{t('scripts.sync_page')}</span>".html_safe, script_sync_path(@script)%></li>
			<% end %>
			<% if (same_user and !@script.locked) or user_is_mod
				if @script.deleted? %>
					<li<%=current_page?(script_undelete_path(@script)) ? ' class="current"'.html_safe : ''%>><%= link_to_unless_current "<span>#{t('scripts.undelete_page')}</span>".html_safe, script_undelete_path(@script)%></li>
				<% else %>
					<li<%=current_page?(script_delete_path(@script)) ? ' class="current"'.html_safe : ''%>><%= link_to_unless_current "<span>#{t('scripts.delete_page')}</span>".html_safe, script_delete_path(@script)%></li>
				<% end
			end %>
		</ul>
		<div id="script-content">
			<%= content_for?(:scripts_content) ? yield(:scripts_content) : yield %>
		</div>
	</section>
<% end %>
<%= render template: 'layouts/application' %>